name=ESP32 BLE Mouse 1.2
version=1.2.0
author=ratotsu
maintainer=ratotsu
sentence=Bluetooth LE Mouse library 1.2 for the ESP32.
paragraph=Bluetooth LE Mouse library 1.2 for the ESP32.
category=Communication
url=https://github.com/ratotsu/ESP32-BLE-Mouse
architectures=esp32
